### ISSUE TITLE
Ajuster le footer

### ISSUE THREAD

**Issue by H-Etien** [Billyma21/reservations-master#11]
Modifier les "X" pour mettre des noms

**Comment by Billyma21** [comment]
Celle qu'on avait pensé lors de la reunion n1, n'est pas optimisé pour le projet, je préfere utilisé la n2, simpe & efficace pour le projet actuel. 
C'est ok pour la 2 ?

**Comment by H-Etien** [comment]
ok pour la 2 mais  faut modifier la dernière partie du texte pour que ça concorde avec la longueur de la page

**Comment by Billyma21** [comment]
C'est fait, tout est ok.
