### ISSUE TITLE
Rajouté paiement succès pour la fin des paiement validé avec succès. 

### ISSUE THREAD

**Issue by Billyma21** [Billyma21/reservations-master#12]
- Tu peux aussi écrire s'il te plait un petit rémerciement pour les commandes éffectuer par exemple, et ajuster les models/Views si il te faut.

**Comment by H-Etien** [comment]
Faut  il ajouter une page ou juste modifier la page paiement actuel ?

**Comment by Billyma21** [comment]
Tu peux carrement ajouté une page s'il faut, et actuelisé celle existante pour qu'elle renvoie vers celle que tu vas crée. 
Pour toi sa va ?

**Comment by H-Etien** [comment]
Ok, Je vais essayer de rajouter la page
Je te notifie si besoin pour la partie page existante
