### ISSUE TITLE
Modification profil

### ISSUE THREAD

**Issue by H-Etien** [Billyma21/reservations-master#18]
Il faudrait quelques paramètres pour pouvoir modifier le profil.

Changer le nom, prénom ou changer le mot de passe,  etc

Juste la base pour pouvoir modifier si l'utilisateur a fait une faut de frappe quand il a créé son profil

**Comment by Billyma21** [comment]
C'est fait, j'ai crée la possibilité de voir l'historique de commande, avec les commande en détaile et les infos de la commande tel que qt, prix, titre, ect. 
 J'ai du rajouté à la bd une table Odere_item. 
 Et le front pour ses pages, je l'ai fais du coup pour évité de revenir dessus.
