### ISSUE TITLE
Réorganisé la Navbar

### ISSUE THREAD

**Issue by Billyma21** [Billyma21/reservations-master#20]
Tu peux réorganisé s'il te plait la navbar, de facon à avoir l'essentiel dessus, et n'hesite pas à faire du front-end pour améliorer le rendu visuel aussi, s'il le faut. 
Merci :)

**Comment by H-Etien** [comment]
1er  draft

- Accueil
- Mon profil
- Liste des Spectacles
- Administration (seulement visible pour les admins)
(- Contact)
